#!/bin/bash

Network_dir="/etc/network"
Service_dir="/etc/systemd/system"
Working_dir="/etc/routing"

Usage() {
    echo "Usage: $0 { start | stop | status }"
    exit 1
}

Parameter_judge() {
    correct_num="$1" 
    real_num="$2" 
    if [ "$correct_num" != "$real_num" ]; then
        Usage
    fi
}


Config() {
    sudo cp $Network_dir/interfaces $Network_dir/if.backup
    sudo cp NIF $Network_dir/interfaces
    sudo mkdir $Working_dir
    sudo cp routing.sh $Working_dir/
    sudo cp ip-route-control $Working_dir/
    sudo cp routing.service $Service_dir/
    sudo cp balance.service $Service_dir/
}

Restore() {
    sudo cp $Network_dir/if.backup $Network_dir/interfaces
    sudo rm $Network_dir/if.backup
    sudo rm -rf $Working_dir
    sudo rm $Service_dir/routing.service
    sudo rm $Service_dir/balance.service
}

Service_start() {
    for action in enable start status
    do 
        sudo systemctl $action routing.service
        sudo systemctl $action balance.service
    done
}

Service_stop() {
    for action in disable stop status
    do
        sudo systemctl $action routing.service
        sudo systemctl $action balance.service
    done
}

Start() {
    Config
    Service_start
}

Stop() {
    Restore
    Service_stop
}

Status() {
    echo "Service"
    sudo systemctl status routing.service
    echo
    echo "ip route"
    ip route
    echo
    echo "iptable"
    sudo iptables -t nat -L POSTROUTING -nv
    sudo iptables -t filter -L FORWARD -nv
}

case "$1" in 
    start)
        Parameter_judge 1 $#
        Start
        ;;

    stop)
        Parameter_judge 1 $#
        Stop
        ;;

    status)
        Parameter_judge 1 $#
        Status
        ;;

    *)
        Usage
        ;;
esac

